site_name: CoPerception

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings

nav:
  - getting started:
    - index.md
    - getting_started/installation.md
    - Github Repo: https://github.com/coperception/coperception
  - tools:
    - tools/index.md
    - tools/det.md
    - tools/seg.md
    - tools/track.md
  - datasets:
    - datasets/v2x_sim.md
  - tutorials:
    - tutorials/individual_models.md
    - tutorials/collaborative_models.md
    - tutorials/visualization.md